version: '3.1'

services:

        consignment-cli:
                build: ./consignment-cli
                environment:
                        MICRO_REGISTRY: "mdns"

        consignment-service:
                build: ./consignment-service
                ports:
                        - 50051:50051
                environment:
                        MICRO_ADRESS: ":50051"
                        MICRO_REGISTRY: "mdns"
                        DBHOST: 'datastore:27017'

        vessel-service:
                build: ./vessel-service
                ports:
                        - 50052:50051
                environment:
                        MICRO_ADDRESS: ":5052"
                        MICRO_REGISTRY: "mdns"
        user-service:
                build: ./user-service
                ports:
                        - 50053:50051
                environment:
                        MICRO_ADDRESS: ":5053"
                        MICRO_REGISTRY: "mdns"
        datastore:
                image: mongo
                ports:
                        - 27017:27017
        database:
                image: postgres
                ports:
                        - 5432:5432
